language: php

php:
  - 5.6
  - 7.0
  - 7.1

sudo: false

install:
  - travis_retry composer install --no-interaction

script:
  - if [ "$TRAVIS_PHP_VERSION" != "5.6" ]; then vendor/bin/phpunit; fi
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then vendor/bin/phpunit --coverage-clover clover.xml; fi

after_script:
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then bash <(curl -s https://codecov.io/bash); fi
